theme: jekyll-theme-merlot
# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#
title : simple site
author :
  name : Julian Kopka Larsen

# NOTE: If replacing this next line with your own URL, you likely want "https://" not "http://"
production_url : https://juliankopkalarsen.github.io
baseurl: /
url: https://juliankopkalarsen.github.io

# jekyll setup
permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed